version: "3"
services:
  app:
    build: .
    container_name: be_eval
    user: root
    entrypoint: /app/entrypoint.sh
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: be_eval
      POSTGRES_HOST : postgres